accounts/urls.py
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django_otp.forms import OTPAuthenticationForm

from . import views

app_name = 'accounts'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.account, name='account'),
    path('change_password/', views.change_password, name='change_password'),
    path('user_instance/create/<int:user_id>/', views.user_instance_create, name='user_instance_create'),
    path('user_instance/<int:pk>/update/', views.user_instance_update, name='user_instance_update'),
    path('user_instance/<int:pk>/delete/', views.user_instance_delete, name='user_instance_delete'),
    path('ssh_key/create/', views.ssh_key_create, name='ssh_key_create'),
    path('ssh_key/<int:pk>/delete/', views.ssh_key_delete, name='ssh_key_delete'),
]

if settings.OTP_ENABLED:
    urlpatterns += [
        path(
            'login/',
            LoginView.as_view(template_name='accounts/otp_login.html', authentication_form=OTPAuthenticationForm),
            name='login',
        ),
        path('email_otp/', views.email_otp, name='email_otp'),
        path('admin_email_otp/<int:user_id>/', views.admin_email_otp, name='admin_email_otp'),
    ]
else:
    urlpatterns += path('login/', LoginView.as_view(template_name='login.html'), name='login'),

logs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("vm_logs/<vname>/", views.vm_logs, name="vm_logs"),
]

accounts/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from instances.models import Instance


class UserInstanceManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('instance', 'user')


class UserInstance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    is_change = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    is_vnc = models.BooleanField(default=False)

    objects = UserInstanceManager()

    def __str__(self):
        return _('Instance "%(inst)s" of user %(user)s') % {"inst": self.instance, "user": self.user}

    class Meta:
        unique_together = ['user', 'instance']


class UserSSHKey(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    keyname = models.CharField(_('key name'), max_length=25)
    keypublic = models.CharField(_('public key'), max_length=500)

    def __str__(self):
        return self.keyname


class UserAttributes(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    can_clone_instances = models.BooleanField(default=True)
    max_instances = models.IntegerField(_('max instances'),
                                        default=2,
                                        help_text=_("-1 for unlimited. Any integer value"),
                                        validators=[
                                            MinValueValidator(-1),
                                        ])
    max_cpus = models.IntegerField(
        _('max CPUs'),
        default=2,
        help_text=_("-1 for unlimited. Any integer value"),
        validators=[MinValueValidator(-1)],
    )
    max_memory = models.IntegerField(
        _('max memory'),
        default=2048,
        help_text=_("-1 for unlimited. Any integer value"),
        validators=[MinValueValidator(-1)],
    )
    max_disk_size = models.IntegerField(
        _('max disk size'),
        default=20,
        help_text=_("-1 for unlimited. Any integer value"),
        validators=[MinValueValidator(-1)],
    )

    def __str__(self):
        return self.user.username


class PermissionSet(models.Model):
    """
    Dummy model for holding set of permissions we need to be automatically added by Django
    """
    class Meta:
        default_permissions = ()
        permissions = (('change_password', _('Can change password')), )

        managed = False

accounts/forms.py
from appsettings.settings import app_settings
from django.contrib.auth import get_user_model
from django.forms import EmailField, Form, ModelForm, ValidationError
from django.utils.translation import gettext_lazy as _

from .models import UserInstance, UserSSHKey
from .utils import validate_ssh_key


class UserInstanceForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserInstanceForm, self).__init__(*args, **kwargs)

        # Make user and instance fields not editable after creation
        instance = getattr(self, 'instance', None)
        if instance and instance.id is not None:
            self.fields['user'].disabled = True
            self.fields['instance'].disabled = True

    def clean_instance(self):
        instance = self.cleaned_data['instance']
        if app_settings.ALLOW_INSTANCE_MULTIPLE_OWNER == 'False':
            exists = UserInstance.objects.filter(instance=instance)
            if exists:
                raise ValidationError(_('Instance owned by another user'))

        return instance

    class Meta:
        model = UserInstance
        fields = '__all__'


class ProfileForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')


class UserSSHKeyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.publickeys = UserSSHKey.objects.filter(user=self.user)
        super().__init__(*args, **kwargs)

    def clean_keyname(self):
        for key in self.publickeys:
            if self.cleaned_data['keyname'] == key.keyname:
                raise ValidationError(_("Key name already exist"))

        return self.cleaned_data['keyname']

    def clean_keypublic(self):
        for key in self.publickeys:
            if self.cleaned_data['keypublic'] == key.keypublic:
                raise ValidationError(_("Public key already exist"))

        if not validate_ssh_key(self.cleaned_data['keypublic']):
            raise ValidationError(_('Invalid key'))
        return self.cleaned_data['keypublic']

    def save(self, commit=True):
        ssh_key = super().save(commit=False)
        ssh_key.user = self.user
        if commit:
            ssh_key.save()
        return ssh_key

    class Meta:
        model = UserSSHKey
        fields = ('keyname', 'keypublic')


class EmailOTPForm(Form):
    email = EmailField(label=_('Email'))

accounts/views.py
from admin.decorators import superuser_only
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from instances.models import Instance

from accounts.forms import EmailOTPForm, ProfileForm, UserSSHKeyForm
from accounts.models import *

from . import forms
from .utils import get_user_totp_device, send_email_with_otp


def profile(request):
    publickeys = UserSSHKey.objects.filter(user_id=request.user.id)
    profile_form = ProfileForm(request.POST or None, instance=request.user)
    ssh_key_form = UserSSHKeyForm()

    if profile_form.is_valid():
        profile_form.save()
        messages.success(request, _("Profile updated"))
        return redirect("accounts:profile")

    return render(
        request,
        "profile.html",
        {
            "publickeys": publickeys,
            "profile_form": profile_form,
            "ssh_key_form": ssh_key_form,
        },
    )


def ssh_key_create(request):
    key_form = UserSSHKeyForm(request.POST or None, user=request.user)
    if key_form.is_valid():
        key_form.save()
        messages.success(request, _("SSH key added"))
        return redirect("accounts:profile")

    return render(
        request,
        "common/form.html",
        {
            "form": key_form,
            "title": _("Add SSH key"),
        },
    )


def ssh_key_delete(request, pk):
    ssh_key = get_object_or_404(UserSSHKey, pk=pk, user=request.user)
    if request.method == "POST":
        ssh_key.delete()
        messages.success(request, _("SSH key deleted"))
        return redirect("accounts:profile")

    return render(
        request,
        "common/confirm_delete.html",
        {
            "object": ssh_key,
            "title": _("Delete SSH key"),
        },
    )


@superuser_only
def account(request, user_id):
    user = User.objects.get(id=user_id)
    user_insts = UserInstance.objects.filter(user_id=user_id)
    instances = Instance.objects.all().order_by("name")
    publickeys = UserSSHKey.objects.filter(user_id=user_id)

    return render(
        request,
        "account.html",
        {
            "user": user,
            "user_insts": user_insts,
            "instances": instances,
            "publickeys": publickeys,
            "otp_enabled": settings.OTP_ENABLED,
        },
    )


@permission_required("accounts.change_password", raise_exception=True)
def change_password(request):
    form = PasswordChangeForm(request.user, request.POST or None)

    if form.is_valid():
        user = form.save()
        update_session_auth_hash(request, user)  # Important!
        messages.success(request, _("Password Changed"))
        return redirect("accounts:profile")

    return render(request, "accounts/change_password_form.html", {"form": form})


@superuser_only
def user_instance_create(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    form = forms.UserInstanceForm(request.POST or None, initial={"user": user})
    if form.is_valid():
        form.save()
        return redirect(reverse("accounts:account", args=[user.id]))

    return render(
        request,
        "common/form.html",
        {
            "form": form,
            "title": _("Create User Instance"),
        },
    )


@superuser_only
def user_instance_update(request, pk):
    user_instance = get_object_or_404(UserInstance, pk=pk)
    form = forms.UserInstanceForm(request.POST or None, instance=user_instance)
    if form.is_valid():
        form.save()
        return redirect(reverse("accounts:account", args=[user_instance.user.id]))

    return render(
        request,
        "common/form.html",
        {
            "form": form,
            "title": _("Update User Instance"),
        },
    )


@superuser_only
def user_instance_delete(request, pk):
    user_instance = get_object_or_404(UserInstance, pk=pk)
    if request.method == "POST":
        user = user_instance.user
        user_instance.delete()
        next = request.GET.get("next", None)
        if next:
            return redirect(next)
        else:
            return redirect(reverse("accounts:account", args=[user.id]))

    return render(
        request,
        "common/confirm_delete.html",
        {"object": user_instance},
    )


def email_otp(request):
    form = EmailOTPForm(request.POST or None)
    if form.is_valid():
        UserModel = get_user_model()
        try:
            user = UserModel.objects.get(email=form.cleaned_data["email"])
        except UserModel.DoesNotExist:
            pass
        else:
            device = get_user_totp_device(user)
            send_email_with_otp(user, device)

        messages.success(request, _("OTP Sent to %(email)s") % {"email": form.cleaned_data["email"]})
        return redirect("accounts:login")

    return render(
        request,
        "accounts/email_otp_form.html",
        {
            "form": form,
            "title": _("Email OTP"),
        },
    )


@superuser_only
def admin_email_otp(request, user_id):
    user = get_object_or_404(get_user_model(), pk=user_id)
    device = get_user_totp_device(user)
    if user.email != "":
        send_email_with_otp(user, device)
        messages.success(request, _("OTP QR code was emailed to user %(user)s") % {"user": user})
    else:
        messages.error(request, _("User email not set, failed to send QR code"))
    return redirect("accounts:account", user.id)

accounts/templates/accounts/change_password_form.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}
{% load icons %}

{% block title %}{%trans "Change Password" %}{% endblock title %}

{% block content %}
<div class="row">
    <div class="offset-2 col-lg-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{%trans "Change Password" %}: {{ user }}</h4>
            </div>
            <div class="card-body">
                <form method="post" id="password-change">
                    {% csrf_token %}
                    {% bootstrap_form form layout='horizontal' %}
                </form>
            </div>
            <div class="card-footer">
                <div class="float-end">
                    <a class="btn btn-primary" href="javascript:history.back()">{% icon 'times' %}
                        {% trans "Cancel" %}</a>
                    <button type="submit" form="password-change" class="btn btn-success">
                        {% icon 'check' %} {% trans "Change" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/email_otp_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load icons %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block page_heading %}{{ title }}{% endblock page_heading %}

{% block content %}
<div class="alert alert-info">
    {% blocktrans %}
    Enter email address OTP QR code will be sent to.
    {% endblocktrans %}
</div>
<div class="card">
    <div class="card-body">
        <form id="create-update" action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
        </form>
    </div>
    <div class="card-footer">
        <div class="mb-0 float-end">
            <a class="btn btn-primary" href="javascript:history.back()">{% icon 'arrow-left' %} {% trans "Cancel" %}</a>
            <button type="submit" form="create-update" class="btn btn-success">
                {% icon 'envelope-o' %} {% trans "Send" %}
            </button>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/otp_login.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}WebVirtCloud{% endblock title %}

{% block page_heading %}WebVirtCloud{% endblock page_heading %}

{% block content %}
<div class="row">
    <div class="col-6 offset-3" role="main">
        <div class="card">
            <div class="card-body">
                {% if form.errors %}
                    {% bootstrap_form_errors form %}
                {% endif %}
                <form class="form-signin" method="post" role="form" aria-label="Login form">
                    {% csrf_token %}
                    {% bootstrap_field form.username layout='horizontal' %}
                    {% bootstrap_field form.password layout='horizontal' %}
                    {% bootstrap_field form.otp_token layout='horizontal' %}
                    <a href="{% url 'accounts:email_otp' %}" class="float-end mb-2">{% trans "I do not have/lost my OTP!" %}</a>
                    <button class="btn btn-lg btn-success btn-block" type="submit">{% trans "Sign In" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}