instances/urls.py
from django.urls import path

from . import views

app_name = 'instances'

urlpatterns = [
    path('', views.index, name='index'),
    path('flavor/create/', views.flavor_create, name='flavor_create'),
    path('flavor/<int:pk>/update/', views.flavor_update, name='flavor_update'),
    path('flavor/<int:pk>/delete/', views.flavor_delete, name='flavor_delete'),
    path('<int:pk>/', views.instance, name='instance'),
    path('<int:pk>/poweron/', views.poweron, name='poweron'),
    path('<int:pk>/powercycle/', views.powercycle, name='powercycle'),
    path('<int:pk>/poweroff/', views.poweroff, name='poweroff'),
    path('<int:pk>/suspend/', views.suspend, name='suspend'),
    path('<int:pk>/resume/', views.resume, name='resume'),
    path('<int:pk>/force_off/', views.force_off, name='force_off'),
    path('<int:pk>/destroy/', views.destroy, name='destroy'),
    path('<int:pk>/migrate/', views.migrate, name='migrate'),
    path('<int:pk>/status/', views.status, name='status'),
    path('<int:pk>/stats/', views.stats, name='stats'),
    path('<int:pk>/osinfo/', views.osinfo, name='osinfo'),
    path('<int:pk>/rootpasswd/', views.set_root_pass, name='rootpasswd'),
    path('<int:pk>/add_public_key/', views.add_public_key, name='add_public_key'),
    path('<int:pk>/resizevm_cpu/', views.resizevm_cpu, name='resizevm_cpu'),
    path('<int:pk>/resize_memory/', views.resize_memory, name='resize_memory'),
    path('<int:pk>/resize_disk/', views.resize_disk, name='resize_disk'),
    path('<int:pk>/add_new_vol/', views.add_new_vol, name='add_new_vol'),
    path('<int:pk>/delete_vol/', views.delete_vol, name='delete_vol'),
    path('<int:pk>/add_owner/', views.add_owner, name='add_owner'),
    path('<int:pk>/add_existing_vol/', views.add_existing_vol, name='add_existing_vol'),
    path('<int:pk>/edit_volume/', views.edit_volume, name='edit_volume'),
    path('<int:pk>/detach_vol/', views.detach_vol, name='detach_vol'),
    path('<int:pk>/add_cdrom/', views.add_cdrom, name='add_cdrom'),
    path('<int:pk>/detach_cdrom/<str:dev>/', views.detach_cdrom, name='detach_cdrom'),
    path('<int:pk>/unmount_iso/', views.unmount_iso, name='unmount_iso'),
    path('<int:pk>/mount_iso/', views.mount_iso, name='mount_iso'),
    path('<int:pk>/snapshot/', views.snapshot, name='snapshot'),
    path('<int:pk>/delete_snapshot/', views.delete_snapshot, name='delete_snapshot'),
    path('<int:pk>/revert_snapshot/', views.revert_snapshot, name='revert_snapshot'),
    path('<int:pk>/set_vcpu/', views.set_vcpu, name='set_vcpu'),
    path('<int:pk>/set_vcpu_hotplug/', views.set_vcpu_hotplug, name='set_vcpu_hotplug'),
    path('<int:pk>/set_autostart/', views.set_autostart, name='set_autostart'),
    path('<int:pk>/unset_autostart/', views.unset_autostart, name='unset_autostart'),
    path('<int:pk>/set_bootmenu/', views.set_bootmenu, name='set_bootmenu'),
    path('<int:pk>/unset_bootmenu/', views.unset_bootmenu, name='unset_bootmenu'),
    path('<int:pk>/set_bootorder/', views.set_bootorder, name='set_bootorder'),
    path('<int:pk>/change_xml/', views.change_xml, name='change_xml'),
    path('<int:pk>/set_guest_agent/', views.set_guest_agent, name='set_guest_agent'),
    path('<int:pk>/set_video_model/', views.set_video_model, name='set_video_model'),
    path('<int:pk>/change_network/', views.change_network, name='change_network'),
    path('<int:pk>/add_network/', views.add_network, name='add_network'),
    path('<int:pk>/delete_network/', views.delete_network, name='delete_network'),
    path('<int:pk>/set_link_state/', views.set_link_state, name='set_link_state'),
    path('<int:pk>/set_qos/', views.set_qos, name='set_qos'),
    path('<int:pk>/unset_qos/', views.unset_qos, name='unset_qos'),
    path('<int:pk>/del_owner/', views.del_owner, name='del_owner'),  # no links to this one???
    path('<int:pk>/clone/', views.clone, name='clone'),
    path('<int:pk>/update_console/', views.update_console, name='update_console'),
    path('<int:pk>/change_options/', views.change_options, name='change_options'),
    path('<int:pk>/getvvfile/', views.getvvfile, name='getvvfile'),  # no links to this one???
    path('create/<int:compute_id>/', views.create_instance_select_type, name='create_instance_select_type'),
    path('create/<int:compute_id>/<str:arch>/<str:machine>/', views.create_instance, name='create_instance'),
    path('guess_mac_address/<vname>/', views.guess_mac_address, name='guess_mac_address'),
    path('guess_clone_name/', views.guess_clone_name, name='guess_clone_name'),
    path('random_mac_address/', views.random_mac_address, name='random_mac_address'),
    path('check_instance/<vname>/', views.check_instance, name='check_instance'),
    path('<int:pk>/sshkeys/', views.sshkeys, name='sshkeys'),
]

logs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("vm_logs/<vname>/", views.vm_logs, name="vm_logs"),
]

instances/views.py
import crypt
import json
import os
import re
import socket
import time
from bisect import insort

from accounts.models import UserInstance, UserSSHKey
from admin.decorators import superuser_only
from appsettings.models import AppSettings
from appsettings.settings import app_settings
from computes.models import Compute
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from instances.models import Instance
from libvirt import VIR_DOMAIN_UNDEFINE_KEEP_NVRAM, VIR_DOMAIN_UNDEFINE_NVRAM, libvirtError
from logs.views import addlogmsg
from vrtManager import util
from vrtManager.create import wvmCreate
from vrtManager.instance import wvmInstances
from vrtManager.interface import wvmInterface
from vrtManager.storage import wvmStorage
from vrtManager.util import randomPasswd

from . import utils
from .forms import ConsoleForm, FlavorForm, NewVMForm
from .models import Flavor


def index(request):
    instances = None

    computes = (
        Compute.objects.all()
        .order_by("name")
        .prefetch_related("instance_set")
        .prefetch_related("instance_set__userinstance_set")
    )
    for compute in computes:
        utils.refr(compute)

    if request.user.is_superuser:
        instances = Instance.objects.all().prefetch_related("userinstance_set")
    else:
        instances = Instance.objects.filter(userinstance__user=request.user).prefetch_related("userinstance_set")

    return render(request, "allinstances.html", {"computes": computes, "instances": instances})


def instance(request, pk):
    instance: Instance = get_instance(request.user, pk)
    compute: Compute = instance.compute
    computes = Compute.objects.all().order_by("name")
    computes_count = computes.count()
    users = User.objects.all().order_by("username")
    publickeys = UserSSHKey.objects.filter(user_id=request.user.id)
    keymaps = settings.QEMU_KEYMAPS
    console_types = AppSettings.objects.get(key="QEMU_CONSOLE_DEFAULT_TYPE").choices_as_list()
    console_form = ConsoleForm(
        initial={
            "type": instance.console_type,
            "listen_on": instance.console_listen_address,
            "password": instance.console_passwd,
            "keymap": instance.console_keymap,
        }
    )
    console_listen_addresses = settings.QEMU_CONSOLE_LISTEN_ADDRESSES
    bottom_bar = app_settings.VIEW_INSTANCE_DETAIL_BOTTOM_BAR
    allow_admin_or_not_template = request.user.is_superuser or request.user.is_staff or not instance.is_template
    try:
        userinstance = UserInstance.objects.get(
            instance__compute_id=compute.id, instance__name=instance.name, user__id=request.user.id
        )
    except UserInstance.DoesNotExist:
        userinstance = None

    memory_range = [256, 512, 768, 1024, 2048, 3072, 4096, 6144, 8192, 16384]
    if instance.memory not in memory_range:
        insort(memory_range, instance.memory)
    if instance.cur_memory not in memory_range:
        insort(memory_range, instance.cur_memory)
    clone_free_names = utils.get_clone_free_names()
    user_quota_msg = utils.check_user_quota(request.user, 0, 0, 0, 0)

    default_bus = app_settings.INSTANCE_VOLUME_DEFAULT_BUS
    default_io = app_settings.INSTANCE_VOLUME_DEFAULT_IO
    default_discard = app_settings.INSTANCE_VOLUME_DEFAULT_DISCARD
    default_zeroes = app_settings.INSTANCE_VOLUME_DEFAULT_DETECT_ZEROES
    default_cache = app_settings.INSTANCE_VOLUME_DEFAULT_CACHE
    default_format = app_settings.INSTANCE_VOLUME_DEFAULT_FORMAT
    # default_disk_owner_uid = int(app_settings.INSTANCE_VOLUME_DEFAULT_OWNER_UID)
    # default_disk_owner_gid = int(app_settings.INSTANCE_VOLUME_DEFAULT_OWNER_GID)

    # clone_instance_auto_name = app_settings.CLONE_INSTANCE_AUTO_NAME

    # try:
    #     instance = Instance.objects.get(compute=compute, name=vname)
    #     if instance.uuid != uuid:
    #         instance.uuid = uuid
    #         instance.save()
    #         msg = _(f"Fixing UUID {uuid}")
    #         addlogmsg(request.user.username, instance.compute.name, instance.name, msg)
    # except Instance.DoesNotExist:
    #     instance = Instance(compute=compute, name=vname, uuid=uuid)
    #     instance.save()
    #     msg = _("Instance does not exist: Creating new instance")
    #     addlogmsg(request.user.username, instance.compute.name, instance.name, msg)

    # userinstances = UserInstance.objects.filter(instance=instance).order_by('user__username')
    userinstances = instance.userinstance_set.order_by("user__username")
    allow_admin_or_not_template = request.user.is_superuser or request.user.is_staff or not instance.is_template

    # Host resources
    vcpu_host = len(instance.vcpu_range)
    memory_host = instance.proxy.get_max_memory()
    bus_host = instance.proxy.get_disk_bus_types(instance.arch, instance.machine)
    networks_host = sorted(instance.proxy.get_networks())
    interfaces_host = sorted(instance.proxy.get_ifaces())
    nwfilters_host = instance.proxy.get_nwfilters()
    storages_host = sorted(instance.proxy.get_storages(True))
    net_models_host = instance.proxy.get_network_models()

    return render(request, "instance.html", locals())


def status(request, pk):
    instance = get_instance(request.user, pk)
    return JsonResponse({"status": instance.proxy.get_status()})


def stats(request, pk):
    instance = get_instance(request.user, pk)
    json_blk = []
    json_net = []

    # TODO: stats are inaccurate
    cpu_usage = instance.proxy.cpu_usage()
    mem_usage = instance.proxy.mem_usage()
    blk_usage = instance.proxy.disk_usage()
    net_usage = instance.proxy.net_usage()

    current_time = time.strftime("%H:%M:%S")
    for blk in blk_usage:
        json_blk.append({"dev": blk["dev"], "data": [int(blk["rd"]) / 1048576, int(blk["wr"]) / 1048576]})

    for net in net_usage:
        json_net.append({"dev": net["dev"], "data": [int(net["rx"]) / 1048576, int(net["tx"]) / 1048576]})

    return JsonResponse(
        {
            "cpudata": int(cpu_usage["cpu"]),
            "memdata": mem_usage,
            "blkdata": json_blk,
            "netdata": json_net,
            "timeline": current_time,
        }
    )

def osinfo(request, pk):
    instance = get_instance(request.user, pk)
    results = instance.proxy.osinfo()
    
    return JsonResponse(results)

def guess_mac_address(request, vname):
    data = {"vname": vname}
    mac = utils.get_dhcp_mac_address(vname)
    if not mac:
        mac = utils.get_random_mac_address()
    data["mac"] = mac
    return HttpResponse(json.dumps(data))


def random_mac_address(request):
    data = dict()
    data["mac"] = utils.get_random_mac_address()
    return HttpResponse(json.dumps(data))


def guess_clone_name(request):
    dhcp_file = "/srv/webvirtcloud/dhcpd.conf"
    prefix = app_settings.CLONE_INSTANCE_DEFAULT_PREFIX
    if os.path.isfile(dhcp_file):
        instance_names = [i.name for i in Instance.objects.filter(name__startswith=prefix)]
        with open(dhcp_file, "r") as f:
            for line in f:
                line = line.strip()
                if f"host {prefix}" in line:
                    fqdn = line.split(" ")[1]
                    hostname = fqdn.split(".")[0]
                    if hostname.startswith(prefix) and hostname not in instance_names:
                        return HttpResponse(json.dumps({"name": hostname}))
    return HttpResponse(json.dumps({}))


def check_instance(request, vname):
    instance = Instance.objects.filter(name=vname)
    data = {"vname": vname, "exists": False}
    if instance:
        data["exists"] = True
    return JsonResponse(data)


def sshkeys(request, pk):
    """
    :param request:
    :param vname:
    :return:
    """
    instance = get_instance(request.user, pk)
    instance_keys = []
    userinstances = UserInstance.objects.filter(instance=instance)

    for ui in userinstances:
        keys = UserSSHKey.objects.filter(user=ui.user)
        for k in keys:
            instance_keys.append(k.keypublic)
    if request.GET.get("plain", ""):
        response = "\n".join(instance_keys)
        response += "\n"
    else:
        response = json.dumps(instance_keys)
    return HttpResponse(response)


def get_instance(user, pk):
    """
    Check that instance is available for user, if not raise 404
    """
    instance = get_object_or_404(Instance, pk=pk)
    user_instances = user.userinstance_set.all().values_list("instance", flat=True)

    if user.is_superuser or instance.id in user_instances:
        return instance
    else:
        raise Http404()


def poweron(request, pk):
    instance = get_instance(request.user, pk)
    if instance.is_template:
        messages.warning(request, _("Templates cannot be started."))
    else:
        instance.proxy.start()
        addlogmsg(request.user.username, instance.compute.name, instance.name, _("Power On"))

    return redirect(request.META.get("HTTP_REFERER"))


def powercycle(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.force_shutdown()
    instance.proxy.start()
    addlogmsg(request.user.username, instance.compute.name, instance.name, _("Power Cycle"))
    return redirect(request.META.get("HTTP_REFERER"))


def poweroff(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.shutdown()
    addlogmsg(request.user.username, instance.compute.name, instance.name, _("Power Off"))

    return redirect(request.META.get("HTTP_REFERER"))


@superuser_only
def suspend(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.suspend()
    addlogmsg(request.user.username, instance.compute.name, instance.name, _("Suspend"))

instances/templates/instances/destroy_instance_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{% trans "Confirm Destroy" %}
{% endblock title %}

{% block page_heading %}
{% trans "Destroy instance" %} {{ instance }}
{% endblock page_heading %}

{% block content %}
{% if request.user.is_superuser or userinstance.is_delete %}
    {% if instance.status == 3 %}
        <div class="alert alert-danger">
            {% trans "Instance is suspended, cannot destroy!" %}
        </div>
    {% else %}
        <div class="alert alert-danger">
            {% trans "This action is irreversible!" %}
        </div>
        <form action="{% url 'instances:destroy' instance.id %}" class="form" method="post" role="form" id="delete_form">{% csrf_token %}
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" name="delete_disk" value="true" checked id="delete_disk">
                <label class="form-check-label fw-bold" for="delete_disk">{% trans "Remove Instance's data" %}</label>
            </div>
            {% if instance.nvram %}    
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" name="delete_nvram" value="true" id="delete_nvram" checked>
                <label class="form-check-label fw-bold" for="delete_nvram">
                    {% trans "Remove Instance's NVRAM" %}
                </label>
            </div>
            {% endif %}
            <button type="submit" class="btn btn-lg btn-success float-end" name="delete">
                {% trans "Destroy" %}
            </button>
        </form>
    {% endif %}
{% else %}
    <div class="alert alert-danger" role="alert">
        {% trans "You cannot destroy instance!" %}
    </div>
{% endif %}
{% endblock content %}

instances/templates/instances/power_tab.html
{% load i18n %}
<div class="tab-pane active" id="power" role="tabpanel">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" aria-label="Instance power actions">
        {% if instance.status == 1 %}
            <li class="nav-item" role="presentation">
                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#poweroff" type="button" role="tab" aria-controls="poweroff" aria-selected="true">
                    {% trans "Power Off" %}
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#powercycle" type="button" role="tab" aria-controls="powercycle" aria-selected="false">
                    {% trans "Power Cycle" %}
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#powerforce" type="button" role="tab" aria-controls="powerforce" aria-selected="false">
                    {% trans "Force Off" %}
                </button>
            </li>
            {% if request.user.is_superuser %}
                <li class="nav-item" role="presentation">
                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#suspend" type="button" role="tab" aria-controls="suspend" aria-selected="false">
                        {% trans "Suspend" %}
                    </button>
                </li>
            {% endif %}
        {% endif %}
        {% if instance.status == 3 %}
            {% if request.user.is_superuser %}
            <li class="nav-item" role="presentation">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#resume" type="button" role="tab" aria-controls="resume" aria-selected="false">
                    {% trans "Resume" %}
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#powerforce" type="button" role="tab" aria-controls="powerforce" aria-selected="false">
                    {% trans "Force Off" %}
                </button>
            </li>
            {% endif %}
        {% endif %}
        {% if instance.status == 5 %}
            <li class="nav-item" role="presentation">
                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#boot" type="button" role="tab" aria-controls="boot" aria-selected="true">
                    {% trans "Power On" %}
                </button>
            </li>
        {% endif %}
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        {% if instance.status == 1 %}
            <div class="tab-pane tab-pane-bordered active" id="poweroff" role="tabpanel" aria-labelledby="poweroff-tab">
                <p>{% trans "This action sends an ACPI shutdown signal to the instance." %}</p>
                <form action="{% url 'instances:poweroff' instance.id %}" method="post" role="form" aria-label0="Power off instance form">
                    {% csrf_token %}
                    <input type="submit" name="poweroff" class="btn btn-lg btn-success float-end" value="{% trans "Power Off" %}">
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="tab-pane tab-pane-bordered" id="powercycle" role="tabpanel" aria-labelledby="powercycle-tab">
                <p>{% trans "This action forcibly powers off and start the instance and may cause data corruption." %}</p>
                <form action="{% url 'instances:powercycle' instance.id %}" method="post" role="form" aria-label="Power cycle instance form">{% csrf_token %}
                    <input type="submit" name="powercycle" class="btn btn-lg btn-success float-end" value="{% trans "Power Cycle" %}">
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="tab-pane tab-pane-bordered" id="powerforce" role="tabpanel" aria-labelledby="powerforce-tab">
                <p>{% trans "This action forcibly powers off the instance and may cause data corruption." %}</p>
                <form action="{% url 'instances:force_off' instance.id %}" method="post" role="form" aria-label="Force to shotdown instance form">
                    {% csrf_token %}
                    <input type="submit" name="powerforce" class="btn btn-lg btn-success float-end" value="{% trans "Force Off" %}">
                    <div class="clearfix"></div>
                </form>
            </div>
            {% if request.user.is_superuser %}
                <div class="tab-pane tab-pane-bordered" id="suspend" role="tabpanel" aria-labelledby="suspend-tab">
                    <p>{% trans "This action suspends the instance." %}</p>
                    <form action="{% url 'instances:suspend' instance.id %}" method="post" role="form" aria-label="Suspend instance form">{% csrf_token %}
                        <input type="submit" name="suspend" class="btn btn-lg btn-success float-end" value="{% trans "Suspend" %}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            {% endif %}
        {% endif %}
        {% if instance.status == 3 %}
            {% if request.user.is_superuser %}
                <div class="tab-pane tab-pane-bordered active" id="resume" role="tabpanel" aria-labelledby="resume-tab">
                    <p>{% trans "This action restore the instance after suspend." %}</p>
                    <form action="{% url 'instances:resume' instance.id %}" method="post" role="form" aria-label="Resume instance from suspension form">{% csrf_token %}
                        <input type="submit" name="resume" class="btn btn-lg btn-success float-end" value="{% trans "Resume" %}">
                        <div class="clearfix"></div>
                    </form>
                </div>
                <div class="tab-pane tab-pane-bordered" id="powerforce" role="tabpanel" aria-labelledby="powerforce-tab">
                    <p>{% trans "This action forcibly powers off the instance and may cause data corruption." %}</p>
                    <form action="{% url 'instances:force_off' instance.id %}" method="post" role="form" aria-label="Force to shutdown form">{% csrf_token %}
                        <input type="submit" name="powerforce" class="btn btn-lg btn-success float-end" value="{% trans "Force Off" %}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            {% else %}
                <div class="tab-pane tab-pane-bordered active" id="resume" role="tabpanel" aria-labelledby="resume-tab">
                    <p>{% trans "Administrator blocked your instance." %}</p>
                    <form action="{% url 'instances:resume' instance.id %}" method="post" role="form" aria-label="Resume instance form">{% csrf_token %}
                        <button class="btn btn-lg btn-success disabled float-end">{% trans "Resume" %}</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            {% endif %}
        {% endif %}
        {% if instance.status == 5 %}
            <div class="tab-pane tab-pane-bordered active" id="boot" role="tabpanel" aria-labelledby="boot-tab">
                <p>{% trans "Click on Power On button to start this instance." %}</p>
                <form action="{% url 'instances:poweron' instance.id %}" method="post" role="form" aria-label="Start instance form">
                    {% csrf_token %}
                    {% if instance.is_template %}
                        <p>{% trans "Template instance cannot be started." %}</p>
                        <input type="submit" name="poweron" class="btn btn-lg btn-success float-end disabled" value="{% trans "Power On" %}">
                    {% else %}
                        <input type="submit" name="poweron" class="btn btn-lg btn-success float-end" value="{% trans "Power On" %}">
                    {% endif %}
                    <div class="clearfix"></div>
                </form>
            </div>
        {% endif %}
    </div>
</div>

instances/templates/instances/snapshots_tab.html
{% load i18n %}
{% load icons %}
<div class="tab-pane" id="snapshots" role="tabpanel">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" aria-label="Instance snapshot menu">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#takesnapshot" type="button" role="tab" aria-controls="takesnapshot" aria-selected="true">
                {% trans "Take Snapshot" %}
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#managesnapshot" type="button" role="tab" aria-controls="managesnapshot" aria-selected="false">
                {% trans "Manage Snapshots" %}
            </button>
        </li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane tab-pane-bordered active" id="takesnapshot">
            <p>{% trans "This may take more than an hour, depending on how much content is on your instance and how large the disk is. It could cause web server timeout.." %}</p>
            <form action="{% url 'instances:snapshot' instance.id %}" method="post" role="form" aria-label="Create snapshot form">
                {% csrf_token %}
                
                    <div class="input-group mb-3">
                        <input type="text" class="form-control form-control-lg" name="name" placeholder="{% trans "Enter Snapshot Name" %}" maxlength="14">
                        <input type="submit" class="btn btn-lg btn-success float-end" name="snapshot" value="{% trans "Take Snapshot" %}" onclick="showPleaseWaitDialog();">
                    </div>
                
                
            </form>
            <div class="clearfix"></div>
        </div>
        <div role="tabpanel" class="tab-pane tab-pane-bordered" id="managesnapshot">
            {% if instance.snapshots %}
                <p>{% trans "Choose a snapshot for restore/delete" %}</p>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <th scope="col">{% trans "Name" %}</th>
                            <th scope="col">{% trans "Date" %}</th>
                            <th scope="colgroup" colspan="2">{% trans "Action" %}</th>
                        </thead>
                        <tbody>
                        {% for snap in instance.snapshots %}
                            <tr>
                                <td><strong>{{ snap.name }}</strong></td>
                                <td>{{ snap.date|date:"M d H:i:s" }}</td>
                                <td style="width:30px;">
                                    <form action="{% url 'instances:revert_snapshot' instance.id %}" method="post" role="form" aria-label="Restore snapshot form">
                                        {% csrf_token %}
                                        <input type="hidden" name="name" value="{{ snap.name }}">
                                        {% if instance.status == 5 %}
                                            <button type="submit" class="btn btn-sm btn-secondary" name="revert_snapshot" title="{% trans 'Revert to this Snapshot' %}" onclick="return confirm('Are you sure?')">
                                                    <span class="fa fa-download"></span>
                                            </button>
                                        {% else %}
                                            <button type="button" class="btn btn-sm btn-secondary disabled"
                                                    title="{% trans "To restore snapshots you need Power Off the instance." %}">
                                                    <span class="fa fa-download"></span>
                                            </button>
                                        {% endif %}
                                    </form>
                                </td>
                                <td style="width:30px;">
                                    <form action="{% url 'instances:delete_snapshot' instance.id %}" method="post" role="form" aria-label="Delete snapshot form">{% csrf_token %}
                                        <input type="hidden" name="name" value="{{ snap.name }}">
                                        <button type="submit" class="btn btn-sm btn-danger" title="{% trans 'Delete Snapshot' %}" onclick="return confirm('{% trans "Are you sure?" %}')">
                                            {% icon 'trash' %}
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>{% trans "You do not have any snapshots" %}</p>
            {% endif %}
        </div>
    </div>
</div>