accounts/urls.py
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django_otp.forms import OTPAuthenticationForm

from . import views

app_name = 'accounts'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.account, name='account'),
    path('change_password/', views.change_password, name='change_password'),
    path('user_instance/create/<int:user_id>/', views.user_instance_create, name='user_instance_create'),
    path('user_instance/<int:pk>/update/', views.user_instance_update, name='user_instance_update'),
    path('user_instance/<int:pk>/delete/', views.user_instance_delete, name='user_instance_delete'),
    path('ssh_key/create/', views.ssh_key_create, name='ssh_key_create'),
    path('ssh_key/<int:pk>/delete/', views.ssh_key_delete, name='ssh_key_delete'),
]

if settings.OTP_ENABLED:
    urlpatterns += [
        path(
            'login/',
            LoginView.as_view(template_name='accounts/otp_login.html', authentication_form=OTPAuthenticationForm),
            name='login',
        ),
        path('email_otp/', views.email_otp, name='email_otp'),
        path('admin_email_otp/<int:user_id>/', views.admin_email_otp, name='admin_email_otp'),
    ]
else:
    urlpatterns += path('login/', LoginView.as_view(template_name='login.html'), name='login'),

instances/urls.py
from django.urls import path

from . import views

app_name = 'instances'

urlpatterns = [
    path('', views.index, name='index'),
    path('flavor/create/', views.flavor_create, name='flavor_create'),
    path('flavor/<int:pk>/update/', views.flavor_update, name='flavor_update'),
    path('flavor/<int:pk>/delete/', views.flavor_delete, name='flavor_delete'),
    path('<int:pk>/', views.instance, name='instance'),
    path('<int:pk>/poweron/', views.poweron, name='poweron'),
    path('<int:pk>/powercycle/', views.powercycle, name='powercycle'),
    path('<int:pk>/poweroff/', views.poweroff, name='poweroff'),
    path('<int:pk>/suspend/', views.suspend, name='suspend'),
    path('<int:pk>/resume/', views.resume, name='resume'),
    path('<int:pk>/force_off/', views.force_off, name='force_off'),
    path('<int:pk>/destroy/', views.destroy, name='destroy'),
    path('<int:pk>/migrate/', views.migrate, name='migrate'),
    path('<int:pk>/status/', views.status, name='status'),
    path('<int:pk>/stats/', views.stats, name='stats'),
    path('<int:pk>/osinfo/', views.osinfo, name='osinfo'),
    path('<int:pk>/rootpasswd/', views.set_root_pass, name='rootpasswd'),
    path('<int:pk>/add_public_key/', views.add_public_key, name='add_public_key'),
    path('<int:pk>/resizevm_cpu/', views.resizevm_cpu, name='resizevm_cpu'),
    path('<int:pk>/resize_memory/', views.resize_memory, name='resize_memory'),
    path('<int:pk>/resize_disk/', views.resize_disk, name='resize_disk'),
    path('<int:pk>/add_new_vol/', views.add_new_vol, name='add_new_vol'),
    path('<int:pk>/delete_vol/', views.delete_vol, name='delete_vol'),
    path('<int:pk>/add_owner/', views.add_owner, name='add_owner'),
    path('<int:pk>/add_existing_vol/', views.add_existing_vol, name='add_existing_vol'),
    path('<int:pk>/edit_volume/', views.edit_volume, name='edit_volume'),
    path('<int:pk>/detach_vol/', views.detach_vol, name='detach_vol'),
    path('<int:pk>/add_cdrom/', views.add_cdrom, name='add_cdrom'),
    path('<int:pk>/detach_cdrom/<str:dev>/', views.detach_cdrom, name='detach_cdrom'),
    path('<int:pk>/unmount_iso/', views.unmount_iso, name='unmount_iso'),
    path('<int:pk>/mount_iso/', views.mount_iso, name='mount_iso'),
    path('<int:pk>/snapshot/', views.snapshot, name='snapshot'),
    path('<int:pk>/delete_snapshot/', views.delete_snapshot, name='delete_snapshot'),
    path('<int:pk>/revert_snapshot/', views.revert_snapshot, name='revert_snapshot'),
    path('<int:pk>/set_vcpu/', views.set_vcpu, name='set_vcpu'),
    path('<int:pk>/set_vcpu_hotplug/', views.set_vcpu_hotplug, name='set_vcpu_hotplug'),
    path('<int:pk>/set_autostart/', views.set_autostart, name='set_autostart'),
    path('<int:pk>/unset_autostart/', views.unset_autostart, name='unset_autostart'),
    path('<int:pk>/set_bootmenu/', views.set_bootmenu, name='set_bootmenu'),
    path('<int:pk>/unset_bootmenu/', views.unset_bootmenu, name='unset_bootmenu'),
    path('<int:pk>/set_bootorder/', views.set_bootorder, name='set_bootorder'),
    path('<int:pk>/change_xml/', views.change_xml, name='change_xml'),
    path('<int:pk>/set_guest_agent/', views.set_guest_agent, name='set_guest_agent'),
    path('<int:pk>/set_video_model/', views.set_video_model, name='set_video_model'),
    path('<int:pk>/change_network/', views.change_network, name='change_network'),
    path('<int:pk>/add_network/', views.add_network, name='add_network'),
    path('<int:pk>/delete_network/', views.delete_network, name='delete_network'),
    path('<int:pk>/set_link_state/', views.set_link_state, name='set_link_state'),
    path('<int:pk>/set_qos/', views.set_qos, name='set_qos'),
    path('<int:pk>/unset_qos/', views.unset_qos, name='unset_qos'),
    path('<int:pk>/del_owner/', views.del_owner, name='del_owner'),  # no links to this one???
    path('<int:pk>/clone/', views.clone, name='clone'),
    path('<int:pk>/update_console/', views.update_console, name='update_console'),
    path('<int:pk>/change_options/', views.change_options, name='change_options'),
    path('<int:pk>/getvvfile/', views.getvvfile, name='getvvfile'),  # no links to this one???
    path('create/<int:compute_id>/', views.create_instance_select_type, name='create_instance_select_type'),
    path('create/<int:compute_id>/<str:arch>/<str:machine>/', views.create_instance, name='create_instance'),
    path('guess_mac_address/<vname>/', views.guess_mac_address, name='guess_mac_address'),
    path('guess_clone_name/', views.guess_clone_name, name='guess_clone_name'),
    path('random_mac_address/', views.random_mac_address, name='random_mac_address'),
    path('check_instance/<vname>/', views.check_instance, name='check_instance'),
    path('<int:pk>/sshkeys/', views.sshkeys, name='sshkeys'),
]

logs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("vm_logs/<vname>/", views.vm_logs, name="vm_logs"),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="WebVirtCloud panel for manage virtual machine">
    <meta name="author" content="anatoliy.guskov@gmail.com">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/wvc-main.min.css" %}" rel="stylesheet" id="wvc_css">

    <!-- WebVirtCloud CSS -->
    <link href="{% static "css/webvirtcloud.css" %}" rel="stylesheet">

    <!-- Aditional CSS -->
    {% block style %}{% endblock %}

    <!-- Custom Fonts -->
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
  </head>

  <body>

    {% if request.user.is_authenticated %}
    {% include 'navbar.html' %}
    {% endif %}

    <div role="main" class="container">
      <div class"row">
        <div>
          <div class="float-end">
            {% block page_heading_extra %}
            {% endblock page_heading_extra %}
          </div>
          <h3 class="ms-0 page-header">
            {% block page_heading %}
            {% endblock page_heading %}
          </h3>
        </div>
      </div>
      {% bootstrap_messages %}
      {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- JavaScript Cookie -->
    <script src="{% static 'js/js.cookie.js' %}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/navbar.html
{% load i18n %}
{% load icons %}
{% load common_tags %}
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark bg-primary mb-3" aria-label="Main top navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">WebVirtCloud</a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav">
        <li class="nav-item {% class_active request '^/instances' %}">
            <a class="nav-link" href="{% url 'instances:index' %}"><i class="fa fa-fw fa-desktop"></i> {% trans "Instances" %}</a>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item {% class_active request '^/computes' %}">
            <a class="nav-link" href="{% url 'computes' %}"><i class="fa fa-fw fa-server"></i> {% trans "Computes" %}</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav ms-auto">
        {% if request.user.is_superuser %}
        <li class="nav-item dropdown {% app_active request 'admin' %}">
          <a class="nav-link" id="administration" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% icon 'wrench' %}
          </a>
          <div class="dropdown-menu" aria-labelledby="administration">
            <a class="dropdown-item {% view_active request 'admin:user_list' %}" href="{% url 'admin:user_list' %}">{% icon 'user-plus' %} {% trans "Users" %}</a>
            <a class="dropdown-item {% view_active request 'admin:group_list' %}" href="{% url 'admin:group_list' %}">{% icon 'users' %} {% trans "Groups" %}</a>
            <a class="dropdown-item {% view_active request 'admin:logs' %}" href="{% url 'admin:logs' %}">{% icon 'list-alt' %} {% trans "Logs" %}</a>
            <a class="dropdown-item {% view_active request 'appsettings' %}" href="{% url 'appsettings' %}">{% icon 'cogs' %} {% trans "Settings" %}</i></a>
          </div>
        </li>
        {% endif %}
        <li class="nav-item dropdown {% class_active request '^/accounts' %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" data-bs-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-fw fa-user"></i> {{ request.user.username }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarUserDropdown">
            {% get_current_language as LANGUAGE_CODE %}
            <a class="dropdown-item disabled" href="#">
              {% trans "Language" %}: <span class="badge bg-secondary">{{ LANGUAGE_CODE }}</span>
            </a>
            <a class="dropdown-item {% view_active request 'accounts:profile' %}" href="{% url 'accounts:profile' %}">{% icon 'vcard' %} {% trans "Profile" %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-fw fa-power-off"></i> {% trans "Log Out" %}</a>
          </div>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/pleasewaitdialog.html
{% load i18n %}
    <!-- Please wait dialog -->
    <div class="modal fade" id="pleaseWaitDialog" tabindex="-1" role="dialog" aria-labelledby="pleaseWaitDialogLabel" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Processing" %}...</h5>
                </div>
                <div class="modal-body">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
function showPleaseWaitDialog() {
    $('#pleaseWaitDialog').modal();
    backgroundJobRunning = true;
}
function hidePleaseWaitDialog() {
    $('#pleaseWaitDialog').modal('hide');
    backgroundJobRunning = false;
}
</script>

templates/search_block.html
{% load i18n %}
<div class="float-end search">
    <input id="filter" class="form-control" type="text" placeholder="{% trans 'Search' %}">
</div>