instances/urls.py
from django.urls import path

from . import views

app_name = 'instances'

urlpatterns = [
    path('', views.index, name='index'),
    path('flavor/create/', views.flavor_create, name='flavor_create'),
    path('flavor/<int:pk>/update/', views.flavor_update, name='flavor_update'),
    path('flavor/<int:pk>/delete/', views.flavor_delete, name='flavor_delete'),
    path('<int:pk>/', views.instance, name='instance'),
    path('<int:pk>/poweron/', views.poweron, name='poweron'),
    path('<int:pk>/powercycle/', views.powercycle, name='powercycle'),
    path('<int:pk>/poweroff/', views.poweroff, name='poweroff'),
    path('<int:pk>/suspend/', views.suspend, name='suspend'),
    path('<int:pk>/resume/', views.resume, name='resume'),
    path('<int:pk>/force_off/', views.force_off, name='force_off'),
    path('<int:pk>/destroy/', views.destroy, name='destroy'),
    path('<int:pk>/migrate/', views.migrate, name='migrate'),
    path('<int:pk>/status/', views.status, name='status'),
    path('<int:pk>/stats/', views.stats, name='stats'),
    path('<int:pk>/osinfo/', views.osinfo, name='osinfo'),
    path('<int:pk>/rootpasswd/', views.set_root_pass, name='rootpasswd'),
    path('<int:pk>/add_public_key/', views.add_public_key, name='add_public_key'),
    path('<int:pk>/resizevm_cpu/', views.resizevm_cpu, name='resizevm_cpu'),
    path('<int:pk>/resize_memory/', views.resize_memory, name='resize_memory'),
    path('<int:pk>/resize_disk/', views.resize_disk, name='resize_disk'),
    path('<int:pk>/add_new_vol/', views.add_new_vol, name='add_new_vol'),
    path('<int:pk>/delete_vol/', views.delete_vol, name='delete_vol'),
    path('<int:pk>/add_owner/', views.add_owner, name='add_owner'),
    path('<int:pk>/add_existing_vol/', views.add_existing_vol, name='add_existing_vol'),
    path('<int:pk>/edit_volume/', views.edit_volume, name='edit_volume'),
    path('<int:pk>/detach_vol/', views.detach_vol, name='detach_vol'),
    path('<int:pk>/add_cdrom/', views.add_cdrom, name='add_cdrom'),
    path('<int:pk>/detach_cdrom/<str:dev>/', views.detach_cdrom, name='detach_cdrom'),
    path('<int:pk>/unmount_iso/', views.unmount_iso, name='unmount_iso'),
    path('<int:pk>/mount_iso/', views.mount_iso, name='mount_iso'),
    path('<int:pk>/snapshot/', views.snapshot, name='snapshot'),
    path('<int:pk>/delete_snapshot/', views.delete_snapshot, name='delete_snapshot'),
    path('<int:pk>/revert_snapshot/', views.revert_snapshot, name='revert_snapshot'),
    path('<int:pk>/set_vcpu/', views.set_vcpu, name='set_vcpu'),
    path('<int:pk>/set_vcpu_hotplug/', views.set_vcpu_hotplug, name='set_vcpu_hotplug'),
    path('<int:pk>/set_autostart/', views.set_autostart, name='set_autostart'),
    path('<int:pk>/unset_autostart/', views.unset_autostart, name='unset_autostart'),
    path('<int:pk>/set_bootmenu/', views.set_bootmenu, name='set_bootmenu'),
    path('<int:pk>/unset_bootmenu/', views.unset_bootmenu, name='unset_bootmenu'),
    path('<int:pk>/set_bootorder/', views.set_bootorder, name='set_bootorder'),
    path('<int:pk>/change_xml/', views.change_xml, name='change_xml'),
    path('<int:pk>/set_guest_agent/', views.set_guest_agent, name='set_guest_agent'),
    path('<int:pk>/set_video_model/', views.set_video_model, name='set_video_model'),
    path('<int:pk>/change_network/', views.change_network, name='change_network'),
    path('<int:pk>/add_network/', views.add_network, name='add_network'),
    path('<int:pk>/delete_network/', views.delete_network, name='delete_network'),
    path('<int:pk>/set_link_state/', views.set_link_state, name='set_link_state'),
    path('<int:pk>/set_qos/', views.set_qos, name='set_qos'),
    path('<int:pk>/unset_qos/', views.unset_qos, name='unset_qos'),
    path('<int:pk>/del_owner/', views.del_owner, name='del_owner'),  # no links to this one???
    path('<int:pk>/clone/', views.clone, name='clone'),
    path('<int:pk>/update_console/', views.update_console, name='update_console'),
    path('<int:pk>/change_options/', views.change_options, name='change_options'),
    path('<int:pk>/getvvfile/', views.getvvfile, name='getvvfile'),  # no links to this one???
    path('create/<int:compute_id>/', views.create_instance_select_type, name='create_instance_select_type'),
    path('create/<int:compute_id>/<str:arch>/<str:machine>/', views.create_instance, name='create_instance'),
    path('guess_mac_address/<vname>/', views.guess_mac_address, name='guess_mac_address'),
    path('guess_clone_name/', views.guess_clone_name, name='guess_clone_name'),
    path('random_mac_address/', views.random_mac_address, name='random_mac_address'),
    path('check_instance/<vname>/', views.check_instance, name='check_instance'),
    path('<int:pk>/sshkeys/', views.sshkeys, name='sshkeys'),
]

logs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("vm_logs/<vname>/", views.vm_logs, name="vm_logs"),
]

instances/models.py
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from libvirt import VIR_DOMAIN_XML_SECURE

from computes.models import Compute
from vrtManager.instance import wvmInstance


class Flavor(models.Model):
    label = models.CharField(_('label'), max_length=12, unique=True)
    memory = models.IntegerField(_('memory'))
    vcpu = models.IntegerField(_('vcpu'))
    disk = models.IntegerField(_('disk'))

    def __str__(self):
        return self.label


class InstanceManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('compute')


class Instance(models.Model):
    compute = models.ForeignKey(Compute, on_delete=models.CASCADE)
    name = models.CharField(_('name'), max_length=120, db_index=True)
    uuid = models.CharField(_('uuid'), max_length=36, db_index=True)
    is_template = models.BooleanField(_('is template'), default=False)
    created = models.DateTimeField(_('created'), auto_now_add=True)

    objects = InstanceManager()

    def __str__(self):
        return f'{self.compute}/{self.name}'

    @cached_property
    def proxy(self):
        return wvmInstance(
            self.compute.hostname,
            self.compute.login,
            self.compute.password,
            self.compute.type,
            self.name,
        )

    @cached_property
    def media(self):
        return self.proxy.get_media_devices()

    @cached_property
    def media_iso(self):
        return sorted(self.proxy.get_iso_media())

    @cached_property
    def disks(self):
        return self.proxy.get_disk_devices()

    @cached_property
    def status(self):
        return self.proxy.get_status()

    @cached_property
    def autostart(self):
        return self.proxy.get_autostart()

    @cached_property
    def bootmenu(self):
        return self.proxy.get_bootmenu()

    @cached_property
    def boot_order(self):
        return self.proxy.get_bootorder()

    @cached_property
    def arch(self):
        return self.proxy.get_arch()

    @cached_property
    def machine(self):
        return self.proxy.get_machine_type()

    @cached_property
    def firmware(self):
        return self.proxy.get_loader()

    @cached_property
    def nvram(self):
        return self.proxy.get_nvram()

    @cached_property
    def vcpu(self):
        return self.proxy.get_vcpu()

    @cached_property
    def vcpu_range(self):
        return self.proxy.get_max_cpus()

    @cached_property
    def cur_vcpu(self):
        return self.proxy.get_cur_vcpu()

    @cached_property
    def vcpus(self):
        return self.proxy.get_vcpus()

    @cached_property
    def get_uuid(self):
        return self.proxy.get_uuid()

    @cached_property
    def memory(self):
        return self.proxy.get_memory()

    @cached_property
    def cur_memory(self):
        return self.proxy.get_cur_memory()

    @cached_property
    def title(self):
        return self.proxy.get_title()

    @cached_property
    def description(self):
        return self.proxy.get_description()

    @cached_property
    def networks(self):
        return self.proxy.get_net_devices()

    @cached_property
    def qos(self):
        return self.proxy.get_all_qos()

    @cached_property
    def telnet_port(self):
        return self.proxy.get_telnet_port()

    @cached_property
    def console_type(self):
        return self.proxy.get_console_type()

    @cached_property
    def console_port(self):
        return self.proxy.get_console_port()

    @cached_property
    def console_keymap(self):
        return self.proxy.get_console_keymap()

    @cached_property
    def console_listen_address(self):
        return self.proxy.get_console_listen_addr()

    @cached_property
    def guest_agent(self):
        return False if self.proxy.get_guest_agent() is None else True

    @cached_property
    def guest_agent_ready(self):
        return self.proxy.is_agent_ready()

    @cached_property
    def video_model(self):
        return self.proxy.get_video_model()

    @cached_property
    def video_models(self):
        return self.proxy.get_video_models(self.arch, self.machine)

    @cached_property
    def snapshots(self):
        return sorted(self.proxy.get_snapshot(), reverse=True, key=lambda k: k['date'])

    @cached_property
    def inst_xml(self):
        return self.proxy._XMLDesc(VIR_DOMAIN_XML_SECURE)

    @cached_property
    def has_managed_save_image(self):
        return self.proxy.get_managed_save_image()

    @cached_property
    def console_passwd(self):
        return self.proxy.get_console_passwd()

    @cached_property
    def cache_modes(self):
        return sorted(self.proxy.get_cache_modes().items())

    @cached_property
    def io_modes(self):
        return sorted(self.proxy.get_io_modes().items())

    @cached_property
    def discard_modes(self):
        return sorted(self.proxy.get_discard_modes().items())

    @cached_property
    def detect_zeroes_modes(self):
        return sorted(self.proxy.get_detect_zeroes_modes().items())

    @cached_property
    def formats(self):
        return self.proxy.get_image_formats()


class PermissionSet(models.Model):
    """
    Dummy model for holding set of permissions we need to be automatically added by Django
    """
    class Meta:
        default_permissions = ()
        permissions = [
            ('clone_instances', 'Can clone instances'),
            ('passwordless_console', _('Can access console without password')),
        ]

        managed = False

instances/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _

from appsettings.models import AppSettings
from webvirtcloud.settings import QEMU_CONSOLE_LISTEN_ADDRESSES, QEMU_KEYMAPS

from .models import Flavor


class FlavorForm(forms.ModelForm):
    class Meta:
        model = Flavor
        fields = '__all__'


class ConsoleForm(forms.Form):
    type = forms.ChoiceField()
    listen_on = forms.ChoiceField()
    generate_password = forms.BooleanField(required=False)
    clear_password = forms.BooleanField(required=False)
    password = forms.CharField(widget=forms.PasswordInput(render_value=True), required=False)
    clear_keymap = forms.BooleanField(required=False)
    keymap = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(ConsoleForm, self).__init__(*args, **kwargs)
        type_choices = ((c, c) for c in AppSettings.objects.get(key="QEMU_CONSOLE_DEFAULT_TYPE").choices_as_list())
        keymap_choices = [('auto', 'Auto')] + list((c, c) for c in QEMU_KEYMAPS)
        self.fields['type'] = forms.ChoiceField(choices=type_choices)
        self.fields['listen_on'] = forms.ChoiceField(choices=QEMU_CONSOLE_LISTEN_ADDRESSES)
        self.fields['keymap'] = forms.ChoiceField(choices=keymap_choices)


class NewVMForm(forms.Form):
    name = forms.CharField(error_messages={'required': _('No Virtual Machine name has been entered')}, max_length=64)
    firmware = forms.CharField(max_length=50, required=False)
    vcpu = forms.IntegerField(error_messages={'required': _('No VCPU has been entered')})
    vcpu_mode = forms.CharField(max_length=20, required=False)
    disk = forms.IntegerField(required=False)
    memory = forms.IntegerField(error_messages={'required': _('No RAM size has been entered')})
    networks = forms.CharField(error_messages={'required': _('No Network pool has been choosen')})
    nwfilter = forms.CharField(required=False)
    storage = forms.CharField(max_length=20, required=False)
    template = forms.CharField(required=False)
    images = forms.CharField(required=False)
    cache_mode = forms.CharField(error_messages={'required': _('Please select HDD cache mode')})
    hdd_size = forms.IntegerField(required=False)
    meta_prealloc = forms.BooleanField(required=False)
    virtio = forms.BooleanField(required=False)
    qemu_ga = forms.BooleanField(required=False)
    mac = forms.CharField(required=False)
    console_pass = forms.CharField(required=False, empty_value="", widget=forms.PasswordInput())
    graphics = forms.CharField(error_messages={'required': _('Please select a graphics type')})
    video = forms.CharField(error_messages={'required': _('Please select a video driver')})
    listener_addr = forms.ChoiceField(required=True, widget=forms.RadioSelect, choices=QEMU_CONSOLE_LISTEN_ADDRESSES)

    def clean_name(self):
        name = self.cleaned_data['name']
        have_symbol = re.match('^[a-zA-Z0-9._-]+$', name)
        if not have_symbol:
            raise forms.ValidationError(_('The name of the virtual machine must not contain any special characters'))
        return name

instances/templates/add_instance_network_block.html
{% load i18n %}
{% if request.user.is_superuser %}
    <button type="button" class="btn btn-success float-end" data-bs-toggle="modal" data-bs-target="#addInstanceNetwork">
        <span class="fa fa-plus" aria-hidden="true"></span>
    </button>

    <!-- Modal pool -->
    <div class="modal fade" id="addInstanceNetwork" tabindex="-1" role="dialog" aria-labelledby="addInstanceNetworkLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Add Instance Network" %}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'instances:add_network' instance.id %}" method="post" action="" role="form" aria-label="Add instance network form">{% csrf_token %}
                        <div class="row">
                            <label class="col-sm-4 col-form-label">{% trans "MAC" %}</label>
                            <div class="col-sm-6">
                                <input type="text" class="form-control" name="add-net-mac">
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-sm-4 col-form-label">{% trans "Network" %}</label>
                            <div class="col-sm-6">
                                <select class="form-select" name="add-net-network">
                                    {% for c_net in networks_host %}
                                        <option value="net:{{ c_net }}">Network {{ c_net }}</option>
                                    {% endfor %}
                                    {% for c_iface in interfaces_host %}
                                        <option value="iface:{{ c_iface }}">Interface {{ c_iface }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-sm-4 col-form-label">{% trans "NWFilter" %}</label>
                            <div class="col-sm-6">
                                <select class="form-select" name="add-net-nwfilter">
                                    <option value="">{% trans "None" %}</option>
                                    {% for nwfilter in nwfilters_host %}
                                        <option value="{{ nwfilter }}">{{ nwfilter }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-primary" name="add_network">{% trans "Add" %}</button>
                </div>
                    </form>
            </div> <!-- /.modal-content -->
        </div> <!-- /.modal-dialog -->
    </div> <!-- /.modal -->
{% endif %}

instances/templates/add_instance_volume.html
{% load i18n %}
{% if request.user.is_superuser %}
    <a href="#addvol" type="button" class="btn btn-success float-end" data-bs-toggle="modal" title="{% trans "Add Volume" %}">
        <span class="fa fa-plus" aria-hidden="true"></span>
    </a>

    <!-- Modal pool -->
    <div class="modal fade" id="addvol" tabindex="-1" role="dialog" aria-labelledby="addInstanceVolumeLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{% trans "Add Instance Volume" %}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <ul class="nav nav-tabs" aria-label="Disk attach type">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" aria-controls="NewDisk" data-bs-toggle="tab" data-bs-target="#NewDisk" type="button" role="tab" aria-selected="true">
                            {% trans 'New Disk' %}
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" aria-controls="ExistingDisk" data-bs-toggle="tab" data-bs-target="#ExistingDisk" type="button" role="tab" aria-selected="true">
                            {% trans 'Existing Disk' %}
                        </button>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="NewDisk">
                        <form action="{% url 'instances:add_new_vol' instance.id %}" method="post" role="form" aria-label="Add new volume to disk form">{% csrf_token %}
                            <div class="modal-body">
                                <p class="fw-bold">{% trans "Volume parameters" %}</p>
                                <div class="row">
                                    <label class="col-sm-3 col-form-label">{% trans "Storage" %}</label>
                                    <div class="col-sm-6">
                                        <select name="storage" class="form-select image-format">
                                            {% for storage in storages_host %}
                                                <option value="{{ storage }}">{{ storage }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-3 col-form-label">{% trans "Name" %}</label>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control" name="name" placeholder="{% trans "Name" %}" required pattern="[a-zA-Z0-9\.\-_]+">
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-3 col-form-label">{% trans "Format" %}</label>
                                    <div class="col-sm-6">
                                        <select name="format" class="form-select image-format">
                                            {% for format in instance.formats %}
                                                <option value="{{ format }}" {% if format == default_format %}selected{% endif %}>{% trans format %}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-3 col-form-label">{% trans "Size" %}</label>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control" name="size" value="10" maxlength="5" required pattern="[0-9]+">
                                    </div>
                                    <label class="col-sm-1 col-form-label">{% trans "GB" %}</label>
                                </div>
                                <div class="row">
                                    <label class="col-sm-3 col-form-label">{% trans "Bus" %}</label>
                                    <div class="col-sm-6">
                                        <select name="bus" class="form-select image-format">
                                            {% for bus in bus_host %}
                                                <option value="{{ bus }}" {% if bus == default_bus %}selected{% endif %}>{% trans bus %}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-3 col-form-label">{% trans "Cache" %}</label>
                                    <div class="col-sm-6">
                                        <select name="cache" class="form-select image-format">
                                            {% for mode, name in instance.cache_modes %}
                                                <option value="{{ mode }}" {% if mode == default_cache %}selected{% endif %}>{% trans name %}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row meta-prealloc">
                                    <label class="col-sm-3 col-form-label">{% trans "Metadata" %}</label>
                                    <div class="col-sm-6">
                                        <input type="checkbox" name="meta_prealloc" value="true">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
                                    <button type="submit" class="btn btn-success" name="add_new_vol">{% trans "Add Volume" %}</button>
                                </div>
                        </form>
                            </div>
                        </div> <!-- /.modal-body -->
                        <div class="tab-pane" id="ExistingDisk">
                            <form action="{% url 'instances:add_existing_vol' instance.id %}" method="post" role="form" aria-label="Add existing volume to instance form">{% csrf_token %}
                                <div class="modal-body">
                                    <p class="fw-bold">{% trans "Volume parameters" %}</p>
                                    <div class="row">
                                        <label class="col-sm-3 col-form-label">{% trans "Storage" %}</label>
                                        <div class="col-sm-6">
                                            <div class="dropdown">
                                                <button id="select_storage" class="btn btn-secondary dropdown-toggle form-control" type="button" data-bs-toggle="dropdown">{% trans 'Select Pool' %}...</button>
                                                <div class="dropdown-menu">
                                                    {% for storage in storages_host %}
                                                        <a class="dropdown-item" href="#" onclick="get_volumes({{ instance.compute.id }}, '{{ storage }}')">{{ storage }}</a>
                                                    {% endfor %}
                                                </div>
                                                <input id="selected_storage" name="selected_storage" hidden/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label class="col-sm-3 col-form-label" >{% trans "Volume" %}</label>
                                        <div class="col-sm-6">
                                            <select id="vols" name="vols" class="form-select" disabled>
                                                <option value="" selected>{% trans 'None' %}</option>
                                                <!-- populate with javascript -->
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label class="col-sm-3 col-form-label">{% trans "Bus" %}</label>
                                        <div class="col-sm-6">
                                            <select name="bus" class="form-select image-format">
                                                {% for bus in bus_host %}
                                                    <option value="{{ bus }}" {% if bus == default_bus %}selected{% endif %}>{% trans bus %}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label class="col-sm-3 col-form-label">{% trans "Cache" %}</label>
                                        <div class="col-sm-6">
                                            <select name="cache" class="form-select image-format">
                                                {% for mode, name in instance.cache_modes %}
                                                    <option value="{{ mode }}" {% if mode == default_cache %}selected{% endif %}>{% trans name %}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
                                    <button type="submit" class="btn btn-success">{% trans "Add Volume" %}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                
            </div> <!-- /.modal-content -->
        </div> <!-- /.modal-dialog -->
    </div> <!-- /.modal -->
{% endif %}

instances/templates/instance_actions.html
{% load i18n %}
{% load icons %}
<form action="" method="post" role="form" aria-label="Shortcut instance action form">{% csrf_token %}
    {% if instance.proxy.instance.info.0 == 5 %}
        {% if instance.is_template %}
            <a href="{% url 'instances:instance' instance.id %}#clone" class="btn btn-sm btn-secondary" title="{% trans "Clone" %}">
                {% icon 'clone' %}
            </a>
        {% else %}
            <a class="btn btn-sm btn-secondary" href="{% url 'instances:poweron' instance.id %}" title="{% trans "Power On" %}">
                {% icon 'play' %}
            </a>
        {% endif %}
        <a class="btn btn-sm btn-secondary disabled" title="{% trans "Suspend" %}">{% icon 'pause' %}</a>
        <a class="btn btn-sm btn-secondary disabled" title="{% trans "Power Off" %}">{% icon 'power-off' %}</a>
        <a class="btn btn-sm btn-secondary disabled" title="{% trans "Power Cycle" %}">{% icon 'refresh' %}</a>
        <button class="btn btn-sm btn-secondary disabled" title="{% trans "VNC Console" %}" disabled>
            <span class="fa fa-eye"></span>
        </button>
    {% endif %}
    {% if instance.proxy.instance.info.0 == 3 %}
        <a class="btn btn-sm btn-secondary" href="{% url 'instances:resume' instance.id %}" title="{% trans "Resume" %}">
            {% icon 'play' %}
        </a>
        <a class="btn btn-sm btn-secondary disabled" title="{% trans "Suspend" %}">{% icon 'pause' %}</a>
        <a class="btn btn-sm btn-secondary" href="{% url 'instances:force_off' instance.id %}" title="{% trans "Force Off" %}">
            {% icon 'power-off' %}
        </a>
        <a class="btn btn-sm btn-secondary disabled" title="{% trans "Power Cycle" %}">{% icon 'refresh' %}</a>
        <button class="btn btn-sm btn-secondary disabled" title="{% trans "VNC Console" %}" disabled>
            <span class="fa fa-eye"></span>
        </button>
    {% endif %}
    {% if instance.proxy.instance.info.0 == 1 %}
        <a class="btn btn-sm btn-secondary disabled" title="{% trans "Power On" %}">{% icon 'play' %}</a>
        <a class="btn btn-sm btn-secondary" href="{% url 'instances:suspend' instance.id %}"
            title="{% trans "Suspend" %}">{% icon 'pause' %}</a>
        <a class="btn btn-sm btn-secondary" href="{% url 'instances:poweroff' instance.id %}">{% icon 'power-off' %}</a>
        <a class="btn btn-sm btn-secondary" href="{% url 'instances:powercycle' instance.id %}">{% icon 'refresh' %}</a>
        <button class="btn btn-sm btn-secondary" type="button" onclick='open_console("{{ instance.compute.id }}-{{ instance.get_uuid }}")'
            title="{% trans "Console" %}">
            <span class="fa fa-eye"></span>
        </button>
    {% endif %}
</form>
{% block script %}
<script>
    function open_console(uuid) {
        url = '{% url 'console' %}?token=' + uuid + '';
        window.open(url, '', 'width=850,height=650')
    }
</script>
{% endblock script %}